version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: suplementos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_suplementos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contrase√±a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - suplementos_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_suplementos"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: suplementos_backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - suplementos_network

  # sera separando el backend del frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: suplementos_frontend
  #   restart: unless-stopped
  #   environment:
  #     #VITE_API_URL: http://localhost:3001/api
  #     VITE_API_URL: http://backend:3001/api   # <--- corregido
  #     VITE_BACKEND_URL: http://backend:3001   # <--- recomendado
  #     CHOKIDAR_USEPOLLING: "true"
  #   ports:
  #     - "5137:5137"
  #   volumes:
  #     - ./frontend:/app
  #     - frontend_node_modules:/app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - suplementos_network

  # NO TENEMOS FRONTEND AQUI POR LO QUE NGINX QUE DEPENDE DEL FRONT LO COMENTAMOS
  # nginx:
  #   image: nginx:alpine
  #   container_name: suplementos_nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - suplementos_network

  redis:
    image: redis:7-alpine
    container_name: suplementos_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - suplementos_network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
  # frontend_node_modules:
  backend_node_modules:

networks:
  suplementos_network:
    driver: bridge
